# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'LegalTap' do
	
pod 'AFNetworking','~> 2.6.3'
pod 'MBProgressHUD'
pod 'IQKeyboardManager'
# pod 'CardIO'
pod 'Appsee'
pod 'libextobjc/EXTScope'
pod 'MTBlockAlertView'
#pod 'QuickBlox'
#pod 'Quickblox-WebRTC'
pod 'PayPal-iOS-SDK'

pod 'Mixpanel'

end
